spring:
  application:
    name: wx-chat
  # 默认 dev 环境
  profiles:
    active: dev
server:
  port: 8899
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:config/log4j2-dev.xml
wx:
  tips:
    subscribeTip: "感谢关注～,作为你的私人助手,有什么问题都可以问我哦！"
    chatGpt: "xxxx"
    aiYa: "xxxx"
    limitTip: "抱歉，当前提问额度已用尽，请${wx.tips.checkPeriod}分钟后再试！"
    #防刷次数wx
    maxTimes: 15
    #防刷时间间隔单位：分钟
    checkPeriod: 30
    # 会话上下文上限
    relatedSessions: 10

wall.proxy: true
#openAI KEY
openAi:
  apiKey: xxxx